<?xml version="1.0" encoding="ASCII"?>
<ResourceModel:App xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ResourceModel="http://www.infineon.com/Davex/Resource.ecore" name="UCPROBE" URI="http://resources/4.0.8/app/UCPROBE/0" description="Configures uC/Probe XMC target code.&#xA;uC/Probe XMC is a Windows application that allows you to read and write the memory of any embedded target processor during run-time, and map those values to a set of virtual controls and indicators placed on a graphical dashboard. &#xA;uC/Probe XMC includes an oscilloscope Control that allows you to plot the value of any of your global variables and I/O registers at very high sampling rates. " mode="NOTSHARABLE" version="4.0.8" minDaveVersion="4.2.4" instanceLabel="UCPROBE_0" appLabel="">
  <properties singleton="true"/>
  <virtualSignals name="dout0" URI="http://resources/4.0.8/app/UCPROBE/0/vs_uart_ch_tx" hwSignal="dout0" hwResource="//@hwResources.0" required="false"/>
  <virtualSignals name="tx" URI="http://resources/4.0.8/app/UCPROBE/0/vs_port_tx" hwSignal="pad" hwResource="//@hwResources.3" required="false"/>
  <virtualSignals name="dx0ins" URI="http://resources/4.0.8/app/UCPROBE/0/vs_uart_ch_rx" hwSignal="dx0ins" hwResource="//@hwResources.0" required="false"/>
  <virtualSignals name="rx" URI="http://resources/4.0.8/app/UCPROBE/0/vs_port_rx" hwSignal="pad" hwResource="//@hwResources.4" required="false"/>
  <virtualSignals name="transmit_buffer_int" URI="http://resources/4.0.8/app/UCPROBE/0/vs_uart_ch_tx_sr" hwSignal="transmit_buffer_int" hwResource="//@hwResources.0" required="false"/>
  <virtualSignals name="tx_int" URI="http://resources/4.0.8/app/UCPROBE/0/vs_nvic_tx_int" hwSignal="signal_in" hwResource="//@hwResources.1" required="false"/>
  <virtualSignals name="standard_receive_int" URI="http://resources/4.0.8/app/UCPROBE/0/vs_uart_ch_rx_sr" hwSignal="standard_receive_int" hwResource="//@hwResources.0" required="false"/>
  <virtualSignals name="rx_int" URI="http://resources/4.0.8/app/UCPROBE/0/vs_nvic_rx_int" hwSignal="signal_in" hwResource="//@hwResources.2" required="false"/>
  <virtualSignals name="RXD_signal" URI="http://resources/4.0.8/app/UCPROBE/0/__pin_vs_port_rx" hwSignal="pin" hwResource="//@hwResources.5"/>
  <virtualSignals name="TXD_signal" URI="http://resources/4.0.8/app/UCPROBE/0/__pin_vs_port_tx" hwSignal="pin" hwResource="//@hwResources.6"/>
  <requiredApps URI="http://resources/4.0.8/app/UCPROBE/0/appres_clk" requiredAppName="CLOCK_XMC4" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.0.8/app/UCPROBE/0/appres_cpu" requiredAppName="CPU_CTRL_XMC4" required="false" requiringMode="SHARABLE"/>
  <hwResources name="UART_CH" URI="http://resources/4.0.8/app/UCPROBE/0/hwres_uart_ch" resourceGroupUri="" required="false" mResGrpUri="peripheral/usic/*/channel/*"/>
  <hwResources name="UART Transmit interrupt" URI="http://resources/4.0.8/app/UCPROBE/0/hwres_nvic_tx_int" resourceGroupUri="" required="false" mResGrpUri="peripheral/cpu/0/nvic/interrupt/*"/>
  <hwResources name="UART Receive interrupt" URI="http://resources/4.0.8/app/UCPROBE/0/hwres_nvic_rx_int" resourceGroupUri="" required="false" mResGrpUri="peripheral/cpu/0/nvic/interrupt/*"/>
  <hwResources name="TXD" URI="http://resources/4.0.8/app/UCPROBE/0/hwres_port_tx" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="RXD" URI="http://resources/4.0.8/app/UCPROBE/0/hwres_port_rx" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="RXD" URI="http://resources/4.0.8/app/UCPROBE/0/__pin_hwres_port_rx" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="TXD" URI="http://resources/4.0.8/app/UCPROBE/0/__pin_hwres_port_tx" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <connections URI="http://resources/4.0.8/app/UCPROBE/0/http://resources/4.0.8/app/UCPROBE/0/vs_port_rx/http://resources/4.0.8/app/UCPROBE/0/vs_uart_ch_rx" systemDefined="true" sourceSignal="rx" targetSignal="dx0ins" srcVirtualSignal="//@virtualSignals.3" targetVirtualSignal="//@virtualSignals.2"/>
  <connections URI="http://resources/4.0.8/app/UCPROBE/0/http://resources/4.0.8/app/UCPROBE/0/vs_uart_ch_tx/http://resources/4.0.8/app/UCPROBE/0/vs_port_tx" systemDefined="true" sourceSignal="dout0" targetSignal="tx" srcVirtualSignal="//@virtualSignals.0" targetVirtualSignal="//@virtualSignals.1"/>
  <connections URI="http://resources/4.0.8/app/UCPROBE/0/http://resources/4.0.8/app/UCPROBE/0/vs_uart_ch_tx_sr/http://resources/4.0.8/app/UCPROBE/0/vs_nvic_tx_int" systemDefined="true" sourceSignal="transmit_buffer_int" targetSignal="tx_int" srcVirtualSignal="//@virtualSignals.4" targetVirtualSignal="//@virtualSignals.5"/>
  <connections URI="http://resources/4.0.8/app/UCPROBE/0/http://resources/4.0.8/app/UCPROBE/0/vs_uart_ch_rx_sr/http://resources/4.0.8/app/UCPROBE/0/vs_nvic_rx_int" systemDefined="true" sourceSignal="standard_receive_int" targetSignal="rx_int" srcVirtualSignal="//@virtualSignals.6" targetVirtualSignal="//@virtualSignals.7"/>
  <connections URI="http://resources/4.0.8/app/UCPROBE/0/http://resources/4.0.8/app/UCPROBE/0/vs_port_rx/http://resources/4.0.8/app/UCPROBE/0/__pin_vs_port_rx" systemDefined="true" sourceSignal="rx" targetSignal="RXD_signal" srcVirtualSignal="//@virtualSignals.3" targetVirtualSignal="//@virtualSignals.8"/>
  <connections URI="http://resources/4.0.8/app/UCPROBE/0/http://resources/4.0.8/app/UCPROBE/0/__pin_vs_port_rx/http://resources/4.0.8/app/UCPROBE/0/vs_port_rx" systemDefined="true" sourceSignal="RXD_signal" targetSignal="rx" srcVirtualSignal="//@virtualSignals.8" targetVirtualSignal="//@virtualSignals.3"/>
  <connections URI="http://resources/4.0.8/app/UCPROBE/0/http://resources/4.0.8/app/UCPROBE/0/vs_port_tx/http://resources/4.0.8/app/UCPROBE/0/__pin_vs_port_tx" systemDefined="true" sourceSignal="tx" targetSignal="TXD_signal" srcVirtualSignal="//@virtualSignals.1" targetVirtualSignal="//@virtualSignals.9"/>
  <connections URI="http://resources/4.0.8/app/UCPROBE/0/http://resources/4.0.8/app/UCPROBE/0/__pin_vs_port_tx/http://resources/4.0.8/app/UCPROBE/0/vs_port_tx" systemDefined="true" sourceSignal="TXD_signal" targetSignal="tx" srcVirtualSignal="//@virtualSignals.9" targetVirtualSignal="//@virtualSignals.1"/>
</ResourceModel:App>
